server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prod_crud_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect